/// Flutter icons RspctIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RspctIcons
///      fonts:
///       - asset: fonts/RspctIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RspctIcons {
  RspctIcons._();

  static const _kFontFam = 'RspctIcons';
  static const String? _kFontPkg = null;

  static const IconData crown_empty = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown_filled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
